### ISSUE TITLE
Make Landing page

### ISSUE THREAD

**Issue by ellrub** [chingu-voyages/v42-geckos-team-12#23]

**Comment by DanielaKuester** [comment]
## Tasks for the Landing Page

# Make the Landing Page UI

- [ ] Big picture of the Hogwarts Coat of Arms
- [ ] Four smaller pictures of the houses (Gryffindor, Slytherin, Ravenclaw, Hufflepuff)
- [ ] Background image: Parchment paper? Magic castle? Magic school?
- [ ] "Start the quiz"-button
- [ ] Footer (License attribution for the used images, link to GitHub repo, link to contributors, copyright + year) --> Maybe as reusable component?
